channels:
  - conda-forge
dependencies:
  - python=3.11
  - pyqt
  - sortednp
  - pip
  - pip:
    - -e ../ecephys
    - -e ../wisc_ecephys_tools
    - -e ../spikeinterface
    - -e ../ephyviewer
    - -e ../discoflow
    - -e ../seahorse