channels:
  - conda-forge
dependencies:
  - python=3.11
  - pyside6 # Probably should be pyside2
  - sortednp
  - pip
  - pip: # Remember, this is very sensitive to order...
    - -e ../kCSD-python --config-settings editable_mode=compat
    - -e ../spikeinterface --config-settings editable_mode=compat
    - -e ../ephyviewer --config-settings editable_mode=compat
    - -e ../ecephys --config-settings editable_mode=compat
    - -e ../wisc_ecephys_tools --config-settings editable_mode=compat
    - -e ../discoflow --config-settings editable_mode=compat
    - -e ../seahorse --config-settings editable_mode=compat
