channels:
  - conda-forge
dependencies:
  - python=3.11
  - pyqt
  - sortednp
  - pip
  - pip:
    - -e ../ecephys --config-settings editable_mode=compat
    - -e ../wisc_ecephys_tools --config-settings editable_mode=compat
    - -e ../spikeinterface --config-settings editable_mode=compat
    - -e ../ephyviewer --config-settings editable_mode=compat
    - -e ../discoflow --config-settings editable_mode=compat
    - -e ../seahorse --config-settings editable_mode=compat